##################################################################
# A Github action used to deploy the Web API to Azure (Prod)
##################################################################

name: Deploy Prod Web API
on:
  workflow_run:
    workflows: ["Publish Web API"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Prod Environment
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy web app using Azure credentials
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "docker.io/ekarton/photos-drive-webapi:latest"
