##################################################################
# A Github action used to deploy the Web API
# More info at https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# Azure info at https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-docker-to-azure-app-service
##################################################################

name: Deploy Web API
on:
  push:
    branches: [main]
    paths:
      - "apps/web-api/**"
      - ".github/workflows/deploy-web-api.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and package app
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp tag for Docker image
        run: echo "TIMESTAMP_TAG=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV

      - name: Create Docker image metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ekarton/photos-drive-webapi
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.TIMESTAMP_TAG }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./apps/web-api
          file: ./apps/web-api/Dockerfile
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}

  deploy-test-app:
    name: Deploy to Test Environment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy web app to Render.com 
        run: |
          curl -f -X POST "${{ secrets.RENDER_DEPLOY_TEST_APP_HOOK_URL }}"

  deploy-prod-app:
    name: Deploy to Prod Environment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy web app using Azure credentials
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "docker.io/ekarton/photos-drive-webapi:latest"
