##################################################################
# A Github action used to build and push the Web API Docker image
##################################################################

name: Publish Web API
on:
  push:
    branches: [main]
    paths:
      - "apps/web-api/**"
      - ".github/workflows/publish-web-api.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build, package, and publish the Web API to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp tag for Docker image
        run: echo "TIMESTAMP_TAG=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV

      - name: Create Docker image metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ekarton/photos-drive-webapi
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.TIMESTAMP_TAG }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./apps/web-api
          file: ./apps/web-api/Dockerfile
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
